# Generated by Django 4.0.5 on 2022-06-29 06:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0002_note_delete_notes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-title']},
        ),
        migrations.AddField(
            model_name='note',
            name='publish_as',
            field=models.CharField(choices=[('1', 'Private'), ('2', 'Public')], default='Public', max_length=30),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
