# Generated by Django 4.0.5 on 2022-06-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0003_alter_note_options_note_publish_as_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=100),
        ),
    ]
