# Generated by Django 4.0.5 on 2022-07-01 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseapp', '0004_alter_note_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(max_length=80),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=15),
        ),
    ]
